# Generated by Django 2.1.4 on 2019-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190317_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
